// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FLyre.WebHost")]
[assembly: AssemblyProductAttribute("FLyre")]
[assembly: AssemblyDescriptionAttribute("A chat prototype")]
[assembly: AssemblyVersionAttribute("0.0.0")]
[assembly: AssemblyFileVersionAttribute("0.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.0";
    }
}
